# Site
name: "Belajar Linux ID"
title: "Belajar Linux ID"
description: "Cari tutorial Linux? Disini tempatnya 😁"
logo: 'assets/images/logo2.png'
favicon: 'assets/images/logo2.png'
baseurl: ""
url: "https://belajarlinux.id"
google_analytics: 'UA-176039983-1'
disqus: 'blinuxid'
mailchimp-list: 'https://belajarlinux.us7.list-manage.com/subscribe?u=61d306c597c61df486f3deb61&id=b13aca407c'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  leon:
    name: leonachild@gmail.com
    display_name: Leon Sastra
    gravatar: dd84917a411ef717c000da8f846050df
    email: leonachild@gmail.com
    web: https://leonsastra.my.id
    twitter: https://www.instagram.com/yonzleon_aw/
    description: "Seorang pemuda yang sangat tertarik untuk mempelajari dunia IT terutama bidang Cloud Computing Sys/Dev/Ops. Bio lengkap saya dapat dilihat pada https://leonsastra.my.id/"
  Imron:
    name: campuz.dragon@gmail.com
    display_name: Imron Rosyadi
    gravatar: 9a902418250a11fb157a7142458f8f48
    email: campuz.dragon@gmail.com
    web: https://imron.my.id
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

  nurhamim:
    name: Nur Hamim
    display_name: Nur Hamim
    avatar: 'assets/images/hamimm.jpg'
    email: hamimistimewa@gmail.com
    web: https://nurhamim.net
    description: "Anak desa yang gemar berkomunitas, suka menulis dan mencari hal baru seputar Unix/Linux dan Cloud. Saat ini sedang menempuh pendidikan S1 TI di Unindra dan kebetulan bekerja di PT Biznet GIO Nusantara"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: categories
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
paginate_trail: 2
paginate_show_first_and_last: true
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-1515372853161377"
adsense-data-ad-slot: "1986938311"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, leon, imron, hamim]
